linters:
  enable:
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosec
    - bodyclose
    - unconvert
    - goconst

issues:
  exclude-use-default: false
  exclude-dirs:
    - protogen
    - vendor
  max-issues-per-linter: 0
  max-same-issues: 0