#version: '3'

services:
  geo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geo
    env_file: ../.env
    networks:
      - geoService-network
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - geoService-network

networks:
  geoService-network:
    external: true