#version: '3'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITLAB_TOKEN: ${GITLAB_TOKEN}
    container_name: user
    restart: always
    env_file: .env
    volumes:
      - gateway-data:/var/lib/postgresql/data
      - ./migrations:/app/migrations
    networks:
      - gateway-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - gateway-data:/var/lib/postgresql/data
    networks:
      - gateway-network

#networks:
#  gateway-network:
#    external: true
networks:
  gateway-network:
    driver: bridge

volumes:
  gateway-data: