#version: '3'

services:
  rates-service:
    build: .
    container_name: rates-service
    restart: unless-stopped
    env_file: .env
    ports:
      - "50051:50051"
      - "9090:9090"
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - rates-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    env_file: .env
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8123/ping" ]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
        - rates-network

networks:
  rates-network:
    driver: bridge

volumes:
  clickhouse-data: