global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'proxy'
    static_configs:
      - targets: ['proxy:8081']

  - job_name: "prometheus"
    static_configs:
      - targets: ['localhost:9090']
