global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rates-service'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "clickhouse"
    static_configs:
      - targets: [ 'clickhouse:9363' ]

  - job_name: "node"
    static_configs:
      - targets: ['node-exporter:9100']
